import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Card from '../components/Cards';
import EventAndProgram from '../components/EventAndProgarm';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Outcomes from '../components/Outcomes';
import Services from '../components/Services';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brainycube Research Organization</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Brainycube Research Organization' message='Keep learning and exploring, you are the future of research!' />
      <About/>
      <Outcomes/>
      <Card/>
      <Slider slides={SliderData} />
      <Services/>
      <EventAndProgram/>
      <Instagram />
    </div>
  );
}
